### ISSUE TITLE
cuda runtime error

### ISSUE THREAD

**Issue by auroua** [blei-lab/edward#234]
When I run the example code  _bayesian_linear_regression.py_. I encounter the follow error:

> /home/aurora/software/anaconda2/bin/python2.7 /home/aurora/hdd/workspace/PycharmProjects/edward/examples/bayesian_linear_regression_plot.py
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.5 locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.5 locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.5 locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.7.5 locally
> Using gpu device 0: GeForce GTX 980 Ti (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 5005)
> F tensorflow/stream_executor/cuda/cuda_driver.cc:316] current context was not created by the StreamExecutor cuda_driver API: 0x4431a20; a CUDA runtime call was likely performed without using a StreamExecutor context

How to resolve this error?

**Comment by dustinvtran** [comment]
Interesting, haven't seen this before. From online searches of the error, it seems to happen when there is another application use CUDA. Edward uses only TensorFlow so I'm not sure how this might happen. Could you provide your TensorFlow version, Python version, and what version of Edward you're running?

**Comment by lfloeer** [comment]
I've recently stumbled onto the same error. For me the reason was the following: I also have PyMC3 and theano installed on my machine. When importing Edward, it also imports theano somewhere along the way and theano then accesses the GPU, causing this error. For me, the solution was to edit the `~/.theanorc`-file to begin with 
```txt
[global]
floatX = float32
device = cpu
```
